Eventos passados
angolaosc/aosf-website pull request #31
Opened 2023-10-14 07:23 UTC by Jacintomuambumba

Bom dia, Espero que estejam Bem, Dei um contributo na parte do Calendarios dos Eventos, uma vem que os eventos do dia 6 já foram realizado decidi, dar um toque lá para não confundir as pessoas que vão ver o calendario pensando que ainda não foi realizado os mesmo eventos, então risquei eles.

![image](https://github.com/angolaosc/aosf-website/assets/85085174/fe75f3b9-37b4-4074-b617-67262b6dab18)

2023-10-14 08:10 UTC, antonio-pedro99 requested changes
Olá, @Jacintomuambumba muito obrigado pela PR.
Gostei tanto dessa PR e estou ansioso para aceitar e mesclar. Porém, deixei alguns comentários básicos.

2023-10-14 08:10 UTC, antonio-pedro99 commented on package.json
> +    "next": "^13.5.4",
Proponho usarmos a versão 13.4.19 mesmo, por favor mude isso.

2023-10-14 08:10 UTC, antonio-pedro99 commented on src/sections/eventCalendar/eventInformations.tsx
> +                                        <p>
Por favor, precisas indentar o código.
Leia mais sobre indentação de código [aqui](https://phpmz.home.blog/2019/06/17/o-que-e-indentacao-de-codigo-qual-e-sua-importancia/)

2023-10-14 08:10 UTC, antonio-pedro99 commented on package-lock.json
Por favor, remova esse ficheiro dessa PR.

2023-10-14 08:10 UTC, antonio-pedro99 commented on src/sections/eventCalendar/eventInformations.tsx
> +    isPastEvent?: boolean,  //Adicinoei esta propriedade para verificaar se o evento já foi realizado ou se ja aconteceu
Eu acho que invés de adicionar esse detalhe aqui, deviamos usar no [EventDayProps](https://github.com/angolaosc/aosf-website/blob/860c32af66723649a634c381f08f96a623bf5b6e/src/sections/eventCalendar/eventInformations.tsx#L13)
Assim, invés de riscar todos os ‘item’ da agenda, riscaremos ou adicionaremos só uma informação, tipo `passado` ou `concluido`.

Seria algo tipo `Sexta-feira, 06’ Outubro 2023 - Kickoff day(Concluído)`
e assim em diante. 

Se riscarmos todos ‘items’ da agenda, as pessoas não vão conseguir ver quais eram os temas abordados, e essa informação é importante.

2023-10-14 08:10 UTC, antonio-pedro99 commented on yarn.lock
vamos também remover esse ficheiro aqui.

2023-10-14 08:28 UTC, Jacintomuambumba commented
Muito Obrigado, Vou Fazer isso Já

2023-10-18 13:00 UTC, antonio-pedro99 commented
Sem feedback adequado

2023-10-18 13:00 UTC, closed without merging