Concluidos
angolaosc/aosf-website pull request #34
Opened 2023-10-20 11:58 UTC by Jacintomuambumba

Team CoDev

Este pull request visa aprimorar a exibição dos eventos  e indicar claramente os eventos que já ocorreram. 
Adicionamos "(CONCLUÍDO)" entre parênteses no final da descrição dos eventos dias dos  passados.

@aosccode
@aoscode
#30

2023-10-20 16:38 UTC, antonio-pedro99 commented
Olá @Jacintomuambumba, muito obrigado pela PR. 
Vi que o Deployment falhou, consegues justificar?

2023-10-21 08:39 UTC, antonio-pedro99 requested changes
Muito obrigado pela PR @Jacintomuambumba 
Estamos quase a mesclar a PR, por favor resolva os comentários abaixo.

2023-10-21 08:39 UTC, antonio-pedro99 commented on package-lock.json
Remover este ficheiro

2023-10-21 08:39 UTC, antonio-pedro99 commented on package.json
Mudar a versão para a versão anterior

2023-10-21 08:39 UTC, antonio-pedro99 commented on package.json
> +    "postcss": "^8.4.31",
Nāo mude a versão

2023-10-21 08:47 UTC, Jacintomuambumba commented
@antonio-pedro99 

Boss, Essas alteração e adição de arquivos estão ocorrer, quando eu faço a instalação das depêndecias ou seja quando executo o coomando

next install
yarn install etc, e não faço propositadamente

2023-10-22 08:14 UTC, antonio-pedro99 commented
@Jacintomuambumba essa branch tem conflitos.
Por outra evita mensagens sem significados nos commits :)

O que significa `ddd` ? hhh

2023-10-22 08:15 UTC, antonio-pedro99 commented on package.json
> +    "postcss": "^8.4.31",
@Jacintomuambumba podes alterar a vers\ao para a anterior?

2023-10-22 08:15 UTC, antonio-pedro99 commented on package.json
> +    "postcss": "^8.4.29",
```suggestion
    "postcss": "8.4.29",
```

2023-10-22 08:20 UTC, antonio-pedro99 approved these changes

2023-10-22 08:20 UTC, antonio-pedro99 commented on src/sections/eventCalendar/index.tsx
> +            <EventInformations day="Sexta-feira, 06’ Outubro 2023 - Kickoff day (CONCLUÍDO)"
```suggestion
            <EventInformation day="Sexta-feira, 06’ Outubro 2023 - Kickoff day (CONCLUÍDO)"
```

2023-10-22 08:20 UTC, antonio-pedro99 commented on src/sections/eventCalendar/index.tsx
> +
```suggestion
```

2023-10-22 08:20 UTC, antonio-pedro99 commented on src/sections/eventCalendar/index.tsx
> +          <EventInformations day="Domingo, 15’ Outubro 2023 - Open-source hackathon, Mediateca de Luanda (CONCLUÍDO)"
```suggestion
          <EventInformation day="Domingo, 15’ Outubro 2023 - Open-source hackathon, Mediateca de Luanda (CONCLUÍDO)"
```

2023-10-22 08:20 UTC, antonio-pedro99 commented on src/sections/eventCalendar/index.tsx
> +          <EventInformations day="Terça-feira, 24’ Outubro 2023 - Workshop day Selenium (Evento Online, registro obrigatório)"
```suggestion
          <EventInformation day="Terça-feira, 24’ Outubro 2023 - Workshop day Selenium (Evento Online, registro obrigatório)"
```

2023-10-22 08:24 UTC, merged